spring.application.name=shopsmart

# Puerto dinámico mediante variables de entorno (por defecto 8080 si no se provee)
server.port=${SERVER_PORT:8080}

# Configuración para alta concurrencia (Tomcat embebido)
server.tomcat.threads.max=200
server.tomcat.threads.min-spare=20
server.tomcat.max-connections=10000

